# Generated by Django 2.1.5 on 2019-01-27 07:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.IntegerField(max_length=10, unique=True, verbose_name='Phone Number')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Personal Detail')),
                ('group', models.CharField(choices=[('NPS', 'Nipuna Prabidhik Sewa'), ('PGM', 'Pokhara Green Mart')], max_length=3)),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 27, 7, 34, 50, 669376, tzinfo=utc), verbose_name='Registered Date'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
