# Generated by Django 2.1.5 on 2019-01-27 12:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190127_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 27, 12, 32, 47, 728425, tzinfo=utc), verbose_name='Registered Date'),
        ),
    ]
