# Generated by Django 2.1.5 on 2019-01-27 12:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190127_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 27, 12, 33, 5, 201539, tzinfo=utc), verbose_name='Registered Date'),
        ),
    ]
