# Generated by Django 2.1.5 on 2019-01-27 08:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ad', models.DateField(default=datetime.date(2019, 1, 27))),
                ('start_time', models.TimeField()),
                ('break_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('check_in', models.BooleanField(default=False)),
                ('o_break', models.BooleanField(default=False)),
                ('check_out', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
