# Generated by Django 2.1.5 on 2019-01-27 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_auto_20190127_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date_ad',
            field=models.DateField(blank=True, null=True),
        ),
    ]
