# Generated by Django 2.1.5 on 2019-01-28 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_auto_20190128_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='date_bs',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
